# Generated by Django 3.1.5 on 2021-01-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_auto_20210126_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='addver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageadd', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
